# Directory pattern
🌐 API:
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**'

🕸️ Web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**'

📚 Docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'

💾 DB:
  - changed-files:
      - any-glob-to-any-file: 'supabase/**'

🔧 CI/CD:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

# Branch pattern
🚀 Feature:
  - head-branch: ['^feature/', '^feat/']
🛠️ Fix:
  - head-branch: ['^fix/']
🚨 Hot Fix:
  - head-branch: ['^hotfix/']
🔄 Refactor:
  - head-branch: ['^refactor/']
