name = "api"
main = "src/index.ts"
compatibility_date = "2024-08-02"

# defaultでドメインつけてくるやつ
workers_dev = false
# カスタムドメインを指定
route = { pattern = "api.peeace.net", custom_domain = true }
[vars]
DOCS_URL = "https://docs.peeace.net"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
