name: PR
on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  assign-author:
    name: Assign Author
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1

  label:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
